name: impciker
description: "A Flutter project for plant disease prediction."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  tflite_flutter: ^0.11.0
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/plant_disease_model.tflite
    - assets/class_names.json